### ISSUE TITLE
How to enable GPU on training

### ISSUE THREAD

**Issue by AlmeidaAlin3** [alirezakazemipour/Mujoco-PPO#3]
Hi, is it possible to enable GPU for training the PPO? I was able to train it, but my GPU was not used and I'm not sure if I should enable it somewhere on the code. Could you please help me?
Thanks! :)

**Comment by alirezakazemipour** [comment]
Hi Aline,
Thank you for your inquiry!
The code has been written a bit amateurly and I'm sorry for that.
Change this line:
https://github.com/alirezakazemipour/Continuous-PPO/blob/863d70e34f7d6c0972da296d69cc744f90bf6d4a/agent.py#L16
to 
```python
torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
```

**Comment by Taotao-Kenny** [comment]
Hi @alirezakazemipour, 

I just follow the above method to use GPU for training, but it will get some errors:
```

Traceback (most recent call last):
  File "main.py", line 53, in <module>
    trainer.step()
  File "/home/tao/Desktop/Continuous-PPO (gpu)/train.py", line 91, in step
    print(dist.log_prob(torch.Tensor(action)))
  File "/home/tao/anaconda3/envs/complex_env/lib/python3.6/site-packages/torch/distributions/normal.py", line 77, in log_prob
    return -((value - self.loc) ** 2) / (2 * var) - log_scale - math.log(math.sqrt(2 * math.pi))
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
Did I do anything wrong?
