### ISSUE TITLE
How to set the seed?

### ISSUE THREAD

**Issue by Taotao-Kenny** [alirezakazemipour/Mujoco-PPO#4]
As the title, how to set the seed to fix all the settings and keep to the same and robust result?

**Comment by alirezakazemipour** [comment]
Hi @Taotao-Kenny!
So sorry by the time I was writing the code, I wasn't concerned to do that and that has slipped through the cracks!

**Comment by Taotao-Kenny** [comment]
Hi @alirezakazemipour!
Okay, I see. Thanks for your reply!
